var React = require('react');

// JS equivalent of github.com/atom/reactionary
const DOM = React.DOM;

var tag = (name, ...args) => {
  var attributes;
  if (args.length && args[0].constructor === Object) {
    attributes = args.shift();
  } else {
    attributes = {};
  }

  return DOM[name](attributes, ...args);
};

var bindTag = (name) => {
  return tag.bind(this, name);
};

// needs to explicitly export all tags :(
export const a = bindTag('a');
export const abbr = bindTag('abbr');
export const address = bindTag('address');
export const area = bindTag('area');
export const article = bindTag('article');
export const aside = bindTag('aside');
export const audio = bindTag('audio');
export const b = bindTag('b');
export const base = bindTag('base');
export const bdi = bindTag('bdi');
export const bdo = bindTag('bdo');
export const big = bindTag('big');
export const blockquote = bindTag('blockquote');
export const body = bindTag('body');
export const br = bindTag('br');
export const button = bindTag('button');
export const canvas = bindTag('canvas');
export const caption = bindTag('caption');
export const cite = bindTag('cite');
export const code = bindTag('code');
export const col = bindTag('col');
export const colgroup = bindTag('colgroup');
export const data = bindTag('data');
export const datalist = bindTag('datalist');
export const dd = bindTag('dd');
export const del = bindTag('del');
export const details = bindTag('details');
export const dfn = bindTag('dfn');
export const dialog = bindTag('dialog');
export const div = bindTag('div');
export const dl = bindTag('dl');
export const dt = bindTag('dt');
export const em = bindTag('em');
export const embed = bindTag('embed');
export const fieldset = bindTag('fieldset');
export const figcaption = bindTag('figcaption');
export const figure = bindTag('figure');
export const footer = bindTag('footer');
export const form = bindTag('form');
export const h1 = bindTag('h1');
export const h2 = bindTag('h2');
export const h3 = bindTag('h3');
export const h4 = bindTag('h4');
export const h5 = bindTag('h5');
export const h6 = bindTag('h6');
export const head = bindTag('head');
export const header = bindTag('header');
export const hr = bindTag('hr');
export const html = bindTag('html');
export const i = bindTag('i');
export const iframe = bindTag('iframe');
export const img = bindTag('img');
export const input = bindTag('input');
export const ins = bindTag('ins');
export const kbd = bindTag('kbd');
export const keygen = bindTag('keygen');
export const label = bindTag('label');
export const legend = bindTag('legend');
export const li = bindTag('li');
export const link = bindTag('link');
export const main = bindTag('main');
export const map = bindTag('map');
export const mark = bindTag('mark');
export const menu = bindTag('menu');
export const menuitem = bindTag('menuitem');
export const meta = bindTag('meta');
export const meter = bindTag('meter');
export const nav = bindTag('nav');
export const noscript = bindTag('noscript');
export const object = bindTag('object');
export const ol = bindTag('ol');
export const optgroup = bindTag('optgroup');
export const option = bindTag('option');
export const output = bindTag('output');
export const p = bindTag('p');
export const param = bindTag('param');
export const picture = bindTag('picture');
export const pre = bindTag('pre');
export const progress = bindTag('progress');
export const q = bindTag('q');
export const rp = bindTag('rp');
export const rt = bindTag('rt');
export const ruby = bindTag('ruby');
export const s = bindTag('s');
export const samp = bindTag('samp');
export const script = bindTag('script');
export const section = bindTag('section');
export const select = bindTag('select');
export const small = bindTag('small');
export const source = bindTag('source');
export const span = bindTag('span');
export const strong = bindTag('strong');
export const style = bindTag('style');
export const sub = bindTag('sub');
export const summary = bindTag('summary');
export const sup = bindTag('sup');
export const table = bindTag('table');
export const tbody = bindTag('tbody');
export const td = bindTag('td');
export const textarea = bindTag('textarea');
export const tfoot = bindTag('tfoot');
export const th = bindTag('th');
export const thead = bindTag('thead');
export const time = bindTag('time');
export const title = bindTag('title');
export const tr = bindTag('tr');
export const track = bindTag('track');
export const u = bindTag('u');
export const ul = bindTag('ul');
export const var_ = bindTag('var');
export const video = bindTag('video');
export const wbr = bindTag('wbr');
export const circle = bindTag('circle');
export const defs = bindTag('defs');
export const ellipse = bindTag('ellipse');
export const g = bindTag('g');
export const line = bindTag('line');
export const linearGradient = bindTag('linearGradient');
export const mask = bindTag('mask');
export const path = bindTag('path');
export const pattern = bindTag('pattern');
export const polygon = bindTag('polygon');
export const polyline = bindTag('polyline');
export const radialGradient = bindTag('radialGradient');
export const rect = bindTag('rect');
export const stop = bindTag('stop');
export const svg = bindTag('svg');
export const text = bindTag('text');
export const tspan = bindTag('tspan');
